[project]
name = "llm-zoomcamp-rag"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "egasmaaeldaly-88", email = "eg.asmaaeldaly@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
llm-zoomcamp-rag = "llm_zoomcamp_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
